export enum EmailTypeEnum {
	// Member e-mails
	ACCOUNT_CREATED = 'ACCOUNT_CREATED',
	ACCOUNT_FORGOT_PASSWORD = 'ACCOUNT_FORGOT_PASSWORD',

	// Payment
	PAYMENT_FAILED = 'PAYMENT_FAILED',

	// Orders
	ORDER_CREATED = 'ORDER_CREATED',
	ORDER_CANCELLED = 'ORDER_CANCELLED',
}

export type EmailType =
	| 'ACCOUNT_CREATED'
	| 'ACCOUNT_FORGOT_PASSWORD'
	| 'PAYMENT_FAILED'
	| 'ORDER_CREATED'
	| 'ORDER_CANCELLED'
